// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9u6whP6VF6MXRKfqJ0aiksNaHEQ4LEng',
    appId: '1:698707570038:web:7f74dda4f05694f94bde57',
    messagingSenderId: '698707570038',
    projectId: 'lostandback-27562',
    authDomain: 'lostandback-27562.firebaseapp.com',
    storageBucket: 'lostandback-27562.firebasestorage.app',
    measurementId: 'G-Y9MV7MZKQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlecsAAakUuv9qss_Ovvx30iGwe5Qhr3o',
    appId: '1:698707570038:android:93267fbeb2e49aea4bde57',
    messagingSenderId: '698707570038',
    projectId: 'lostandback-27562',
    storageBucket: 'lostandback-27562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmZ83CRXgJWB4Bw0EYdrsiYeprlPy1xg',
    appId: '1:698707570038:ios:4bd9ce12c0a474854bde57',
    messagingSenderId: '698707570038',
    projectId: 'lostandback-27562',
    storageBucket: 'lostandback-27562.firebasestorage.app',
    iosBundleId: 'com.example.lostandback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmZ83CRXgJWB4Bw0EYdrsiYeprlPy1xg',
    appId: '1:698707570038:ios:4bd9ce12c0a474854bde57',
    messagingSenderId: '698707570038',
    projectId: 'lostandback-27562',
    storageBucket: 'lostandback-27562.firebasestorage.app',
    iosBundleId: 'com.example.lostandback',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9u6whP6VF6MXRKfqJ0aiksNaHEQ4LEng',
    appId: '1:698707570038:web:cdd4c24b58da8eb64bde57',
    messagingSenderId: '698707570038',
    projectId: 'lostandback-27562',
    authDomain: 'lostandback-27562.firebaseapp.com',
    storageBucket: 'lostandback-27562.firebasestorage.app',
    measurementId: 'G-LN6E59SM0Y',
  );
}
